[workspace]

[package]
name = "example1"
version = "0.1.0"
edition = "2024"

[dependencies]
fluent-typed = { path = "../..", features = ["langneg"] }
flate2 = { version = "1.1" }

[build-dependencies]
fluent-typed = { path = "../..", features = ["build", "langneg"] }
flate2 = { version = "1.1" }
